Change screen display of progress
Removed the tracing output from the finished routines. I found that
the screen was alarmingly silent as progress was made.

Added an output to the user for each cert or key saved to a file.
This seems to keep the screen from staying silent for too long.

Signed-off-by: Ronald Lamoreaux <gitkey@chindraba.work>

diff --git a/certsplitter b/certsplitter
--- a/certsplitter
+++ b/certsplitter
@@ -11,13 +11,13 @@ rsa_filter=':23'
 
 # Routine for error condition messages and aborting.
 report_error() { # message
-    printf "ERROR: %s Aborting.\n" "$1" >&2
+    printf "\nERROR: %s Aborting.\n" "$1" >&2
     exit 1
 }
 
 # Routine for reporting that there is nothing to do, for whatever reason
 report_nothing() { # message
-    printf "%s Nothing to do.\n" "$1" >&2
+    printf "\n%s Nothing to do.\n" "$1" >&2
     exit 1
 }
 
@@ -62,7 +62,6 @@ check_prime() { # keyring_path cert_id
 
 # Extract a key, or cert, from the keyring
 extract_key() { # dir config target algo save_dir [('asc')|'gpg' [('key')|'cert [('pub')|'sec' [pass]]]]
-printf " IN: %s %s\n" "extract_key" "$(printf "%s " $@)" >&2
     key_name="${2^^}_user"
     pfx_name="${2^^}_pfx"
     file_pfx="${!pfx_name}"
@@ -78,10 +77,12 @@ printf " IN: %s %s\n" "extract_key" "$(printf "%s " $@)" >&2
     fi
     if [ 'cert' == "${7,,}" ]; then
         target=$3
-        target_label='cert'
+        file_label='cert'
+        note_label='certifcate'
     else
         target="$3!"
-        target_label='key'
+        file_label='key'
+        note_label="$7"
     fi
     if [ 'sec' == "${8,,}" ]; then
         export_type='-secret-key'
@@ -93,7 +94,8 @@ printf " IN: %s %s\n" "extract_key" "$(printf "%s " $@)" >&2
         export_label='pub'
     fi
     [ -z "$9" ] && pass='' || pass="$9"
-    file_note="${4^^} $note_type ${8,,} for ${!key_name}"
+    file_note="${4^^} $note_type $note_label for ${!key_name}"
+    printf "Saving %s in %s format ... " "$file_note" $format
     printf "%s" "$pass" |
     gpg \
         --homedir $1 \
@@ -102,11 +104,12 @@ printf " IN: %s %s\n" "extract_key" "$(printf "%s " $@)" >&2
         --expert \
         --pinentry-mode loopback \
         --passphrase-fd 0 \
-        --output "$5/${!pfx_name}.${4,,}.$target_label.$export_label.${format,,}" \
+        --output "$5/${!pfx_name}.${4,,}.$file_label.$export_label.${format,,}" \
         --comment "$file_note" $armor \
-        --export$export_type $target
+        --export$export_type $target 2>/dev/null
     [ 0 == $? ] || \
         report_error "Saving of $note in $format format failed."
+    printf " DONE \n"
 }
 
 # Change the passpharse on a certificate
@@ -160,9 +163,8 @@ store_cert_pair() { # ring_id data_prefix
 
 # Extract the primary key to files for storage
 store_prime() { # keyring_path key_id data_pfx
-printf " IN: %s %s\n" "store_prime" "$(printf "%s " $@)" >&2
     # save the primary public key
-    extract_key "$1" "${3,,}" "${2// /}" "$4" "$export_dir" 'asc' 'key' 'pub'
+    extract_key "$1" "${3,,}" "${2// /}" "$4" "$export_dir" 'asc' 'primary key' 'pub'
     # save the full public cert
     extract_key "$1" "${3,,}" "${2// /}" "$4" "$export_dir" 'asc' 'cert' 'pub'
     # save the full secret cert
@@ -170,9 +172,9 @@ printf " IN: %s %s\n" "store_prime" "$(printf "%s " $@)" >&2
     # change the passphrase for backup files
     new_pass "$1" "${2// /}" "${pass_main}" "${prime_base}${pass_base}${3^^}"
     # save the primary secret key and full secret cert in asc and gpg formats
-    extract_key "$1" "${3,,}" "${2// /}" "$4" "$import_dir" 'asc' 'key' 'sec' "${prime_base}${pass_base}${3^^}"
+    extract_key "$1" "${3,,}" "${2// /}" "$4" "$import_dir" 'asc' 'primary key' 'sec' "${prime_base}${pass_base}${3^^}"
     extract_key "$1" "${3,,}" "${2// /}" "$4" "$import_dir" 'asc' 'cert' 'sec' "${prime_base}${pass_base}${3^^}"
-    extract_key "$1" "${3,,}" "${2// /}" "$4" "$import_dir" 'gpg' 'key' 'sec' "${prime_base}${pass_base}${3^^}"
+    extract_key "$1" "${3,,}" "${2// /}" "$4" "$import_dir" 'gpg' 'primary key' 'sec' "${prime_base}${pass_base}${3^^}"
     extract_key "$1" "${3,,}" "${2// /}" "$4" "$import_dir" 'gpg' 'cert' 'sec' "${prime_base}${pass_base}${3^^}"
     # reset the passphrase from above
     new_pass "$1" "${2// /}" "${prime_base}${pass_base}${3^^}" "${pass_main}"
